### ISSUE TITLE
Improve installation guide

### ISSUE THREAD

**Issue by kdev** [daniel-zint/nshud#1]
Hey, thanks for your effort!

I had a small problem when trying to use telnet. There's no guide on how to setup telnet in the CSGO launch options. 
It would be great to add this to the guide.
You can find it with some research (it's just `-netconport 2121`) but adding it would be easier and fitting.

**Comment by daniel-zint** [comment]
hey,

Yes you are completely right. I did not update the readme since I added telnet. I will do that.

There is also the spec.html which I haven't mentioned in the readme yet. It contains camera transitions that can be used during freezetime or pauses. I will also explain how to use them.

If you have more ideas, please let me know!

**Comment by daniel-zint** [comment]
I added the explanation of how to use telnet and what it is used for to the readme. I hope that helps.
